### ISSUE TITLE
How to style single.html style

### ISSUE THREAD

**Issue by nikitavoloboev** [calintat/minimal#10]
Currently, I created a simple about me page which uses single.html layout. 

However I don't quite get where do I specify styles for it. Currently, the hyperlinks cannot be seen at all.

**Comment by calintat** [comment]
Hi, I don't understand what you mean. Have you figured it out?

**Comment by nikitavoloboev** [comment]
I wanted to style the website to have a black theme but changing any of the values in the CSS for some reason did not change anything. 

![2017-08-06 at 21 30](https://user-images.githubusercontent.com/6391776/29006372-8750a81e-7aee-11e7-8131-58ced6fa0b83.png)

I wanted to have something like this implemented.
