### ISSUE TITLE
On the mobile version of the website the top menu cannot be dismissed with a click

### ISSUE THREAD

**Issue by nikitavoloboev** [calintat/minimal#12]
For example if I click here : 

![test](https://user-images.githubusercontent.com/6391776/28970259-29ce4d4e-7928-11e7-879b-10d5eb8385fc.png)

The top menu should dismiss I believe but it does not.

**Comment by calintat** [comment]
Sorry but that's how the Bootstrap navigation bar works.

**Comment by anthonylavado** [comment]
@nikitavoloboev I've briefly tested adding this to the footer partial of the HTML (just before the body tag is closed), and it seems to work.

```
    <script>
	$(document).on('click',function(){
    $('.collapse').collapse('hide');
})
    </script> 
```

**Comment by calintat** [comment]
@anthonylavado, I added your script to the theme. Thank you!
