### ISSUE TITLE
How to change topbar text on mobile

### ISSUE THREAD

**Issue by nikitavoloboev** [calintat/minimal#15]
On Desktop, Minimal theme will show Home on the top like here : 

![2017-08-07 at 19 39](https://user-images.githubusercontent.com/6391776/29038491-256242f6-7ba8-11e7-91b6-1d644c991e96.png)

However on mobile that text changes to my name for some reason : 

![test](https://user-images.githubusercontent.com/6391776/29038501-2dbd8a0a-7ba8-11e7-9f85-0f97c9756fdb.png)

Is it possible to have 'Home' shown there too or some other text I specify?

**Comment by calintat** [comment]
Hi, to change the text shown on the top of the navigation bar on mobile, just change [this line](https://github.com/calintat/minimal/blob/master/layouts/partials/header.html#L24).

**Comment by PaulRBerg** [comment]
To make an update on this, to change that title now you have to:

1. Override "partials/header.html"
2. Replace `{{ .Title }}` on [this line](https://github.com/calintat/minimal/blob/master/layouts/partials/header.html#L45) with whatever you want, for instance`{{ .Site.Title }}
