### ISSUE TITLE
Show social buttons on mobile 

### ISSUE THREAD

**Issue by nikitavoloboev** [calintat/minimal#17]
Currently on mobile, the home page looks different to Desktop. On desktop you get a row of options user specifies + a row of social buttons like here : 

![2017-08-17 at 02 58](https://user-images.githubusercontent.com/6391776/29391497-0ae88e74-82f8-11e7-9d27-2b0c7c9ed092.png)

On mobile however, it does not even show social buttons anywhere. The home screen looks like this : 

![2017-08-17 02 57 38](https://user-images.githubusercontent.com/6391776/29391513-1e1f63be-82f8-11e7-9b76-deeab58e4a5c.jpg)

Would it be possible to configure the theme to show social button row here : 

![2017-08-17 02 57 38](https://user-images.githubusercontent.com/6391776/29391525-32b4ce2c-82f8-11e7-8aed-f6754e1f4274.png)

This would be a lot more useful that what is currently shown.

Thank you.

**Comment by oneleaftea** [comment]
Clicking the upper right menu expansion exposes the menu and the social buttons, on a mobile device. IMO, it is already very functional and looks very elegant and perfect the way it is.

**Comment by nikitavoloboev** [comment]
Oh you are right @oneleaftea 

I had to scroll though to see the social buttons. Thought they were gone completely.
