### ISSUE TITLE
Some Disqus Related Tweaks?

### ISSUE THREAD

**Issue by oneleaftea** [calintat/minimal#19]
Hi,
This theme is truly awesome! I was wondering if you could add a few tweaks in regards to Disqus?

1. Currently, Disqus Comments show up with full width on every browser I have tried, such that it looks like letters are running off the page. Is it possible to make it narrower to match the style of the theme?
2. Also, I made a pull request to turn off comments in the front-matter, using "disable_comments" variable. Hope this can be useful. 

Thanks!

**Comment by calintat** [comment]
Hi, the pull request has been merged and I updated the comments section (it's no longer full width).
