### ISSUE TITLE
Changing the title of the content pages

### ISSUE THREAD

**Issue by solmos** [calintat/minimal#2]
How can I change the title of the Posts and Projects pages? 

I changed the titles of the [[menu.main]] items in config.toml to something different. The new names show up in the main menu bar but not in the pages, which still have the original titles Posts and Projects.

**Comment by calintat** [comment]
Hi, those pages are generated by Hugo using the [list](https://github.com/calintat/minimal/blob/master/layouts/_default/list.html) default template. The page title is automatically generated from the name of the subdirectory of `content` in which the files are located. For example, files in the `content/post` directory will be shown as a list at `your-url/post` with the title "Posts". Please note that the title is the plural of the name of the directory (this is Hugo's default behaviour but it can be changed by adding `pluralizelisttitles = false` in your `config`). So to change the titles of the pages, just rename the subdirectories to whatever you want and disable pluralisation if necessary.
