### ISSUE TITLE
About me Section

### ISSUE THREAD

**Issue by vasim07** [calintat/minimal#24]
The theme is awesome! Perfect for me.

Can you add an About Me section where developer can update details about him/her.

I can add one similar to post or project but that about me becomes a blog content which is not suitable for about me section.

Regards,
Vasim Shaikh

**Comment by mariosangiorgio** [comment]
Are you looking for something like [this](https://mariosangiorgio.github.io/page/about/)?

If so, there is no need for extra features. Just add a page [like this one](https://github.com/mariosangiorgio/personal-website/blob/master/content/page/about.md).

**Comment by vasim07** [comment]
Thank you! That's exactly what I was looking for!!! 

Perfect, Thanks a lot.

Regards,
Vasim Shaikh
