### ISSUE TITLE
Add support for a small image to be added

### ISSUE THREAD

**Issue by nikitavoloboev** [calintat/minimal#29]
It would be quite awesome if users could add an image of their choice and it would show above the name. 

Perhaps with rounded corners. I don't think it would subtract from the minimalism of this theme and it can be an optional setting.

**Comment by jamestharpe** [comment]
You can copy `index.html to your site's `/layouts` directory and change it there.

**Comment by calintat** [comment]
You can now add a profile pic on the home page using `profilePic` in `config.toml`.
