### ISSUE TITLE
RSS feed integration

### ISSUE THREAD

**Issue by vncntvandriessche** [calintat/minimal#30]
I'm looking for support for RSS feeds (I like using RSS feeds myself)

Willing to look into it myself if I could get some directions of course!

**Comment by jamestharpe** [comment]
Hugo does this out of the box and the minimal theme supports it already by embedding '{{ .RSSLink }}` in the `header.html` file. Are you looking for more than that? If so, what specifically?

**Comment by vncntvandriessche** [comment]
@jamestharpe Thanks for clearing that up, I now see that the site actually generates the link.

It seems the generated site isn't actually displaying the link though? Am I doing something wrong?

**Comment by jamestharpe** [comment]
Make sure don't have `disableRSS = true` in your `config.toml`. You might also try setting it explicitly to `false`. Also make sure your theme is up-to-date.

**Comment by vncntvandriessche** [comment]
I've tried all of your suggestions, but now that I think about it it seems logical to me that there's no visible link to the RSS feed, as there's no element in the body-section of the generated HTML to show the link?

**Comment by jamestharpe** [comment]
Ooohhh... you want a VISIBLE link 😃 ! IME, RSS readers understand the `<link ...` code and a visible link isn't usually necessary. That said, you can add this by adding a `[[menu.icon]]` entry in your `config.toml`. Here's an example:

```
[[menu.icon]]
    url = "/index.xml"
    name = "rss"
    weight = 6
```

**Comment by jamestharpe** [comment]
A note on how this works, in case you (or anyone else) wants to add more icons to the `menu.icon` - the `name` of the `menu-icon` entry just has to match an `fa-` class from [Font-Awesome](http://fontawesome.io/icons/).

**Comment by vncntvandriessche** [comment]
@jamestharpe That is what I was looking for and BEYOND 😆 .

Thank you so much!
