### ISSUE TITLE
Asciidoc admonition not displayed

### ISSUE THREAD

**Issue by lburgazzoli** [calintat/minimal#33]
I've created s simple [project](https://github.com/lburgazzoli/hugo-asciidoc) using asciidoctor to write post and I want to use admonitions icon but they are not properly displayed. I've followed the [icons](https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/icons.adoc) doc but even adding the icons attribute as suggested, I can't get admonitions to be displayed.

**Comment by jamestharpe** [comment]
Hey there - I'm not familiar with asciidoctor or "admonitions" - can you state more specifically how you'd like **minimal** to change?

**Comment by lburgazzoli** [comment]
Well, that's a good question :) I do not even know if it is an issue with minimal but I know that if I create a simple asciidoc document and I translate it to html, I see admonitions (http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/) but when the same document is rendered using hugo and minimal, such images are lost

**Comment by jamestharpe** [comment]
I doubt this has something to do with minimal, unless it works as expected in other themes. Most likely you need to create an issue with Hugo or Ascii Doctor.

**Comment by lburgazzoli** [comment]
Going to close it and reopen if needed
