### ISSUE TITLE
Did something break with netlify?

### ISSUE THREAD

**Issue by rsangole** [calintat/minimal#36]
Hello,
This isn't an issue with your repo per say. I had a working website for the past many months (forked your code.. and modified it considerably for my own purposes).

But today, it looks really wierd on all my browsers:
http://rsangole.netlify.com

Did netlify break? Why has this happened suddenly?

Rahul

**Comment by Tafkas** [comment]
The https://bootswatch.com/solar/bootstrap.css gives a 404 error.

**Comment by rsangole** [comment]
Thanks @Tafkas. They have a version 3 and version 4 now, which broke the link.
