### ISSUE TITLE
Is it possible to add a line break in config description?

### ISSUE THREAD

**Issue by nikitavoloboev** [calintat/minimal#37]
For example in my case on [my website](https://nikitavoloboev.xyz/). Is it possible to add a line break after this line? 

![2017-11-05 at 23 34](https://user-images.githubusercontent.com/6391776/32419884-f40c1fc6-c281-11e7-9822-967eb36b2e3d.png)

So that `Currently` starts on new line?

**Comment by jamestharpe** [comment]
I haven't tried this myself, but I believe that if you add `<br/>` before "Currently" then you'll get the desired behavior.

**Comment by nikitavoloboev** [comment]
Thank you @jamestharpe 

This works.
