### ISSUE TITLE
It doesn't find /css/main.css

### ISSUE THREAD

**Issue by nikitavoloboev** [calintat/minimal#4]
Not fully sure why but it doesn't seem that minimal reads /css/main.css imported [here](https://github.com/calintat/minimal/blob/master/layouts/partials/css.html#L24).

Also [Prettier](https://github.com/prettier/prettier) formatter formats highlight.js import like this : 

![2017-07-30 at 23 45](https://user-images.githubusercontent.com/6391776/28757340-1dc398a6-7581-11e7-819e-c7522f0f9df2.png)

And it stops working. It has to be one the same line for some reason. :(

**Comment by calintat** [comment]
Hi, the issue is indeed on that line so just change it back.
