### ISSUE TITLE
Font type error

### ISSUE THREAD

**Issue by codigobash** [calintat/minimal#40]
i has changed my font type on .toml

`font = "Josefin+Slab" `

but doesnt work, the link generated is 

`https://fonts.googleapis.com/css?family=Josefin%2bSlab`

and i need

`https://fonts.googleapis.com/css?family=Josefin+Slab`

**Comment by abdiasriver** [comment]
i change directly on the css..

**Comment by calintat** [comment]
Hi, just remove the `+` from the font name.
