### ISSUE TITLE
Change order of blog post/projects

### ISSUE THREAD

**Issue by scottcwebdev** [calintat/minimal#44]
Hello,

How would I change the order that the blog posts/projects show up on the list pages?

For example, if the order is:

Project #3
Project #2
Project #1

and I want to change it to...

Project #1
Project #2
Project #3

**Comment by jamestharpe** [comment]
Copy the `list.html` file from `themes/minimal/layouts/_default` to `layouts/_default` then add `.Reverse` to the `range` call:

```
{{ range (.Paginator 5).Pages.Reverse }} {{ partial "list-item" . }} {{ end }}
```

**Comment by calintat** [comment]
You can also change the ordering by specifying a `weight` in the front matter of a post/project.

**Comment by scottcwebdev** [comment]
Thank you so much! Awesome layout btw
