### ISSUE TITLE
How to create a regular page ?

### ISSUE THREAD

**Issue by L0g4n** [calintat/minimal#64]
What is the preferred way to create a regular single page, e.g. an about page ?

**Comment by calintat** [comment]
For an about page, you'd need a file `/content/about.md` in the same style as posts/projects.

**Comment by L0g4n** [comment]
Hey,
yea this is the most forward way, i thought of that too, but then the about page has the same style as a regular post (e.g. with the date and/or users would be able to comment on it).

Does this mean that only posts and projects (that have no "content" by default as posts) are supported and i would have to customize the template ?
