### ISSUE TITLE
should I need to copy main.css?

### ISSUE THREAD

**Issue by tjaartvdwalt** [calintat/minimal#7]
Thanks for a cool theme.

I am a Hugo newbie, so forgive me if this is a dumb question.

Before the css would work for me I had to copy the file `themes/minimal/static/css/main.css` to `static/css/main.css`. Is this a required step, or is something else wrong?

**Comment by calintat** [comment]
Hi, that shouldn't be necessary. What happens if you don't copy the file?

**Comment by tjaartvdwalt** [comment]
Oops, not sure what happened there. Initially I got an error message in Devtools to  the effect "could not find main.css".

After I deleted the copied file, and clearing my browser cache everything is working :)
