### ISSUE TITLE
Create a new main.menu

### ISSUE THREAD

**Issue by patarol** [calintat/minimal#77]
I'm trying to create a new item in the `[[menu.main]]`, say `About Me`. 

I tried to do something like:

```
[[menu.main]]
--
   url = "/about_me/"
   name = "About Me"
   weight = 4
```
Then I've created a directory in my content directory and it works. 

However it gets the same structure as posts and project. 
I would like to do something like by cliking in the `About Me` menu, just show a text with the description (written in `.md`) and not a post like page.

Is that possible to do something like that?

[Here´s](https://htr3n.github.io/about/) an example.

thank you

**Comment by erolrecep** [comment]
He explains [here](https://github.com/calintat/minimal/issues/64#issuecomment-375993506)
